ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore

  # Disputed scanner issue https://github.com/anchore/grype/issues/504
  - vulnerability: CVE-2002-0493
  - vulnerability: CVE-2013-2185
  - vulnerability: CVE-2016-5425
  - vulnerability: CVE-2016-6325
  - vulnerability: CVE-2020-8022
  - vulnerability: CVE-2022-42800

  # https://nvd.nist.gov/vuln/detail/CVE-2020-35527  https://ubuntu.com/security/CVE-2020-35527
  # In SQLite 3.31.1, there is an out of bounds access problem through ALTER TABLE for views that have a nested FROM clause.
  # SQLite is not leverage by this image. A fix appears to be in progress.
  - vulnerability: CVE-2020-35527
    fix-state: "not-fixed"

  # https://github.com/advisories/GHSA-mjmj-j48q-9wg2
  # A proposed fix is planned for snakeyaml 1.34. For the time being, adding this to
  # the ignore list it is embedded the JMX exporter java agent library which takes in a yaml
  # config file as a JVM argument -- there is no practical way for a malicious party to 
  # leverage this vulnerability. Additionally this library is not leveraged by default. 
  - vulnerability: GHSA-mjmj-j48q-9wg2
    fix-state: "not-fixed"
